"""empty message

Revision ID: 1d8e1742395c
Revises: 2faeca62add6
Create Date: 2017-05-16 15:06:28.660819

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1d8e1742395c'
down_revision = '2faeca62add6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=64), nullable=True),
    sa.Column('description', sa.String(length=256), nullable=True),
    sa.Column('create_date', sa.DateTime(), nullable=True),
    sa.Column('update_date', sa.DateTime(), nullable=True),
    sa.Column('favorites', sa.Integer(), nullable=True),
    sa.Column('has_accepted_answer', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_questions_create_date'), 'questions', ['create_date'], unique=False)
    op.create_index(op.f('ix_questions_update_date'), 'questions', ['update_date'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_questions_update_date'), table_name='questions')
    op.drop_index(op.f('ix_questions_create_date'), table_name='questions')
    op.drop_table('questions')
    # ### end Alembic commands ###
