"""empty message

Revision ID: 35bedde9dfb3
Revises: 4132ca0853a9
Create Date: 2017-05-12 21:37:45.213032

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '35bedde9dfb3'
down_revision = '4132ca0853a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('articles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=64), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=1), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('create_date', sa.DateTime(), nullable=True),
    sa.Column('update_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_articles_create_date'), 'articles', ['create_date'], unique=False)
    op.create_index(op.f('ix_articles_update_date'), 'articles', ['update_date'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_articles_update_date'), table_name='articles')
    op.drop_index(op.f('ix_articles_create_date'), table_name='articles')
    op.drop_table('articles')
    # ### end Alembic commands ###
