"""empty message

Revision ID: 3f3ca14ae589
Revises: 86176cf40634
Create Date: 2017-05-16 18:49:08.265531

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f3ca14ae589'
down_revision = '86176cf40634'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('qtags', sa.Column('tag', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('qtags', 'tag')
    # ### end Alembic commands ###
