"""empty message

Revision ID: 86176cf40634
Revises: 1d8e1742395c
Create Date: 2017-05-16 16:44:29.811619

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '86176cf40634'
down_revision = '1d8e1742395c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('qtags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('qtags')
    # ### end Alembic commands ###
